# Generated by Django 5.2 on 2025-04-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Ubicación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
        ),
        migrations.AddField(
            model_name='activo',
            name='codigo',
            field=models.CharField(default='GEN-0001', max_length=50, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('mant', 'En mantenimiento'), ('baja', 'Dado de baja')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestion_activos.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_activos.ubicacion'),
        ),
    ]
