# Generated by Django 5.2 on 2025-06-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0002_categoria_ubicacion_activo_codigo_activo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_activos.categoria'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activo',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('mant', 'En mantenimiento'), ('baja', 'Dado de baja')], default='activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_activos.ubicacion'),
        ),
    ]
