# Generated by Django 5.2 on 2025-06-19 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion_activos', '0004_activo_responsable_alter_activo_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREACIÓN', 'Creación'), ('ACTUALIZACIÓN', 'Actualización'), ('ELIMINACIÓN', 'Eliminación')], max_length=20, verbose_name='Acción')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID del Objeto')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Objeto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Acción',
                'verbose_name_plural': 'Registros de Acciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
