# Generated by Django 5.2 on 2025-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_activos', '0006_alter_activo_id_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='info_personal_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ci',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_contacto',
            field=models.CharField(max_length=20, verbose_name='Teléfono de Contacto'),
        ),
    ]
